AllCops:
  Exclude:
    - 'Gemfile'
    - db/**/*
    - data/*
    - data_exploration/*
    - spec/**/*

  TargetRubyVersion: 2.3.1
  TargetRailsVersion: 5.1

Metrics/LineLength:
  Severity: refactor
  Max: 120

Metrics/MethodLength:
  Max: 20

metrics/ClassLength:
  Max: 150

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
